### PR TITLE
Allow users to disable overview panel blur

### LINKED ISSUE #65: Bug/feature request/Question?: Unable to set transparent background
Tried with `panelColor = rgba(00000000)` and it still just doesn't seem to wanna do anything like that - is it even possible to set blur/transparency for the panel?

### PR DESCRIPTION
**Pull request by notaoeu**
Fixes #65 and #81

### CODE REVIEW

**Comment by myamusashi** [comment]
Change CColor to CHyprColor

**Comment by notaoeu** [comment]
Accidentally pushed an incomplete set of changes. I will try to work on replacing all instances of CColor with CHyprColor in a more complete manner.

**Comment by notaoeu** [comment]
And I accidentally closed it (send help)

**Comment by KZDKM** [comment]
Thanks!

> Change CColor to CHyprColor

good call

**Pull request merged**
