### PR TITLE
fix: wrong cast type

### LINKED ISSUE #56: When the hyprgrass plug-in is also enabled, touching the touchscreen with your finger will cause the hyprspace plug-in to fail and return to normal after reloading
When the hyprgrass plug-in is also enabled, touching the touchscreen with your finger will cause the hyprspace plug-in to fail and return to normal after reloading

### PR DESCRIPTION
**Pull request by horriblename**
fixes #56

I also updated hyprland input since it's causing `nix build` to fail

### CODE REVIEW

**Comment by myamusashi** [comment]
Is it? I don't use nixOS but it failed on me

**Comment by KZDKM** [comment]
Sorry for the late response, was bogged down with schoolwork. According to upstream documentation on touch events, all the arguments are passed as non-pointer types. The mouse movement and key / mouse button event handlers are all functional so I doubt that the touch events should be cast to pointer types. As with touch functions, I currently dont have any touchscreens to test it on.

Source: 
2024-10-29-171853_screenshot

**Comment by horriblename** [comment]
> According to upstream documentation on touch events, all the arguments are passed as non-pointer types. 

I changed from pointer to non-pointer though. and I did test it and it works

**Comment by horriblename** [comment]
I can help with touch screen stuff + I plan on adding mouse/swipe features to touch later, so don't worry about touch too much :)

**Comment by KZDKM** [comment]
wtf am I having a stroke, how did I read the diff the other way around.

My bad, the change for input handlers lgtm. I dont use nix so I dont know about whats going on in the flakes. But I will merge for now.

**Comment by KZDKM** [comment]
> I can help with touch screen stuff + I plan on adding mouse/swipe features to touch later, so don't worry about touch too much :)

Of course, please do!

**Pull request merged**
